-- MySQL Script generated by MySQL Workbench
-- Fri Jan  8 14:41:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CAhorros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CAhorros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CAhorros` DEFAULT CHARACTER SET utf8 ;
USE `CAhorros` ;

-- -----------------------------------------------------
-- Table `CAhorros`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAhorros`.`Horario` (
  `horario_id` INT NOT NULL AUTO_INCREMENT,
  `horario_ingreso` VARCHAR(45) NOT NULL,
  `horario_salida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`horario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAhorros`.`Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAhorros`.`Banco` (
  `banco_id` INT NOT NULL AUTO_INCREMENT,
  `banco_nombre` VARCHAR(45) NOT NULL,
  `Banco_ubicacion` VARCHAR(45) NOT NULL,
  `Banco_telefono` VARCHAR(10) NOT NULL,
  `Banco_correo` VARCHAR(45) NOT NULL,
  `Horario_horario_id` INT NOT NULL,
  PRIMARY KEY (`banco_id`, `Horario_horario_id`),
  INDEX `fk_Banco_Horario1_idx` (`Horario_horario_id` ASC) VISIBLE,
  CONSTRAINT `fk_Banco_Horario1`
    FOREIGN KEY (`Horario_horario_id`)
    REFERENCES `CAhorros`.`Horario` (`horario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAhorros`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAhorros`.`Empleado` (
  `empleado_id` INT NOT NULL AUTO_INCREMENT,
  `empleado_cargo` VARCHAR(45) NOT NULL,
  `Banco_banco_id` INT NOT NULL,
  `Banco_Horario_horario_id` INT NOT NULL,
  PRIMARY KEY (`empleado_id`),
  INDEX `fk_Empleado_Banco1_idx` (`Banco_banco_id` ASC, `Banco_Horario_horario_id` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Banco1`
    FOREIGN KEY (`Banco_banco_id` , `Banco_Horario_horario_id`)
    REFERENCES `CAhorros`.`Banco` (`banco_id` , `Horario_horario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAhorros`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAhorros`.`Persona` (
  `per_cedula` INT NOT NULL,
  `per_nombre` VARCHAR(45) NOT NULL,
  `per_apellido` VARCHAR(45) NOT NULL,
  `per_direccion` VARCHAR(45) NOT NULL,
  `per_telefono` VARCHAR(10) NOT NULL,
  `per_correo` VARCHAR(45) NOT NULL,
  `per_edad` VARCHAR(45) NOT NULL,
  `Empleado_empleado_id` INT NOT NULL,
  PRIMARY KEY (`per_cedula`, `Empleado_empleado_id`),
  INDEX `fk_Persona_Empleado1_idx` (`Empleado_empleado_id` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Empleado1`
    FOREIGN KEY (`Empleado_empleado_id`)
    REFERENCES `CAhorros`.`Empleado` (`empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAhorros`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAhorros`.`Cuenta` (
  `cuenta_id` INT NOT NULL AUTO_INCREMENT,
  `cuenta_numero` VARCHAR(45) NOT NULL,
  `cuenta_saldo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cuenta_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAhorros`.`Creditos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAhorros`.`Creditos` (
  `creditos_id` INT NOT NULL AUTO_INCREMENT,
  `creditos_aprobacion` VARCHAR(1) NOT NULL,
  `creditos_monto` DOUBLE NOT NULL,
  PRIMARY KEY (`creditos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAhorros`.`Recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAhorros`.`Recibo` (
  `recibo_id` INT NOT NULL AUTO_INCREMENT,
  `recibo_fecha` VARCHAR(45) NOT NULL,
  `recibo_saldo` DOUBLE NOT NULL,
  PRIMARY KEY (`recibo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAhorros`.`LibroDiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAhorros`.`LibroDiario` (
  `lib_id` INT NOT NULL AUTO_INCREMENT,
  `lib_fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lib_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAhorros`.`Transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAhorros`.`Transaccion` (
  `transaccion_id` INT NOT NULL AUTO_INCREMENT,
  `transaccion_tipo` VARCHAR(45) NOT NULL,
  `transaccion_monto` DOUBLE NOT NULL,
  `transaccion_fecha` VARCHAR(45) NOT NULL,
  `Recibo_recibo_id` INT NOT NULL,
  `LibroDiario_lib_id` INT NOT NULL,
  PRIMARY KEY (`transaccion_id`, `Recibo_recibo_id`, `LibroDiario_lib_id`),
  INDEX `fk_Transaccion_Recibo1_idx` (`Recibo_recibo_id` ASC) VISIBLE,
  INDEX `fk_Transaccion_LibroDiario1_idx` (`LibroDiario_lib_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transaccion_Recibo1`
    FOREIGN KEY (`Recibo_recibo_id`)
    REFERENCES `CAhorros`.`Recibo` (`recibo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaccion_LibroDiario1`
    FOREIGN KEY (`LibroDiario_lib_id`)
    REFERENCES `CAhorros`.`LibroDiario` (`lib_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAhorros`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAhorros`.`Cliente` (
  `cli_id` INT NOT NULL,
  `cli_contrasena` VARCHAR(45) NULL,
  `Banco_banco_id` INT NOT NULL,
  `Cuenta_cuenta_id` INT NOT NULL,
  `Persona_per_cedula` INT NOT NULL,
  `Persona_Empleado_empleado_id` INT NOT NULL,
  PRIMARY KEY (`cli_id`, `Persona_per_cedula`, `Persona_Empleado_empleado_id`),
  INDEX `fk_Cliente_Banco_idx` (`Banco_banco_id` ASC) VISIBLE,
  INDEX `fk_Cliente_Cuenta1_idx` (`Cuenta_cuenta_id` ASC) VISIBLE,
  INDEX `fk_Cliente_Persona1_idx` (`Persona_per_cedula` ASC, `Persona_Empleado_empleado_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Banco`
    FOREIGN KEY (`Banco_banco_id`)
    REFERENCES `CAhorros`.`Banco` (`banco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Cuenta1`
    FOREIGN KEY (`Cuenta_cuenta_id`)
    REFERENCES `CAhorros`.`Cuenta` (`cuenta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Persona1`
    FOREIGN KEY (`Persona_per_cedula` , `Persona_Empleado_empleado_id`)
    REFERENCES `CAhorros`.`Persona` (`per_cedula` , `Empleado_empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAhorros`.`PlanCuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAhorros`.`PlanCuentas` (
  `plan_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`plan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAhorros`.`Cuenta_has_Creditos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAhorros`.`Cuenta_has_Creditos` (
  `Cuenta_cuenta_id` INT NOT NULL,
  `Creditos_creditos_id` INT NOT NULL,
  PRIMARY KEY (`Cuenta_cuenta_id`, `Creditos_creditos_id`),
  INDEX `fk_Cuenta_has_Creditos_Creditos1_idx` (`Creditos_creditos_id` ASC) VISIBLE,
  INDEX `fk_Cuenta_has_Creditos_Cuenta1_idx` (`Cuenta_cuenta_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cuenta_has_Creditos_Cuenta1`
    FOREIGN KEY (`Cuenta_cuenta_id`)
    REFERENCES `CAhorros`.`Cuenta` (`cuenta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuenta_has_Creditos_Creditos1`
    FOREIGN KEY (`Creditos_creditos_id`)
    REFERENCES `CAhorros`.`Creditos` (`creditos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CAhorros`.`Cuenta_has_Transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAhorros`.`Cuenta_has_Transaccion` (
  `Cuenta_cuenta_id` INT NOT NULL,
  `Transaccion_transaccion_id` INT NOT NULL,
  PRIMARY KEY (`Cuenta_cuenta_id`, `Transaccion_transaccion_id`),
  INDEX `fk_Cuenta_has_Transaccion_Transaccion1_idx` (`Transaccion_transaccion_id` ASC) VISIBLE,
  INDEX `fk_Cuenta_has_Transaccion_Cuenta1_idx` (`Cuenta_cuenta_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cuenta_has_Transaccion_Cuenta1`
    FOREIGN KEY (`Cuenta_cuenta_id`)
    REFERENCES `CAhorros`.`Cuenta` (`cuenta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuenta_has_Transaccion_Transaccion1`
    FOREIGN KEY (`Transaccion_transaccion_id`)
    REFERENCES `CAhorros`.`Transaccion` (`transaccion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
