-- MySQL Script generated by MySQL Workbench
-- Sun Jan 24 17:37:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cahorros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cahorros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cahorros` DEFAULT CHARACTER SET utf8 ;
USE `cahorros` ;

-- -----------------------------------------------------
-- Table `cahorros`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cahorros`.`horario` (
  `horario_id` INT NOT NULL AUTO_INCREMENT,
  `horario_ingreso` VARCHAR(45) NOT NULL,
  `horario_salida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`horario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cahorros`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cahorros`.`banco` (
  `banco_id` INT NOT NULL AUTO_INCREMENT,
  `banco_nombre` VARCHAR(45) NOT NULL,
  `Banco_ubicacion` VARCHAR(45) NOT NULL,
  `Banco_telefono` VARCHAR(10) NOT NULL,
  `Banco_correo` VARCHAR(45) NOT NULL,
  `Horario_horario_id` INT NOT NULL,
  PRIMARY KEY (`banco_id`, `Horario_horario_id`),
  INDEX `fk_Banco_Horario1_idx` (`Horario_horario_id` ASC) VISIBLE,
  CONSTRAINT `fk_Banco_Horario1`
    FOREIGN KEY (`Horario_horario_id`)
    REFERENCES `cahorros`.`horario` (`horario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cahorros`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cahorros`.`cuenta` (
  `cuenta_id` INT NOT NULL AUTO_INCREMENT,
  `cuenta_numero` VARCHAR(45) NOT NULL,
  `cuenta_saldo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cuenta_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cahorros`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cahorros`.`persona` (
  `per_cedula` VARCHAR(10) NOT NULL,
  `per_nombre` VARCHAR(45) NOT NULL,
  `per_apellido` VARCHAR(45) NOT NULL,
  `per_direccion` VARCHAR(45) NOT NULL,
  `per_telefono` VARCHAR(10) NOT NULL,
  `per_correo` VARCHAR(45) NOT NULL,
  `per_edad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`per_cedula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cahorros`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cahorros`.`cliente` (
  `cli_id` INT NOT NULL,
  `cli_contrasena` VARCHAR(45) NULL DEFAULT NULL,
  `Banco_banco_id` INT NOT NULL,
  `Cuenta_cuenta_id` INT NOT NULL,
  `persona_per_cedula` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`cli_id`, `persona_per_cedula`),
  INDEX `fk_Cliente_Banco_idx` (`Banco_banco_id` ASC) VISIBLE,
  INDEX `fk_Cliente_Cuenta1_idx` (`Cuenta_cuenta_id` ASC) VISIBLE,
  INDEX `fk_cliente_persona1_idx` (`persona_per_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Banco`
    FOREIGN KEY (`Banco_banco_id`)
    REFERENCES `cahorros`.`banco` (`banco_id`),
  CONSTRAINT `fk_Cliente_Cuenta1`
    FOREIGN KEY (`Cuenta_cuenta_id`)
    REFERENCES `cahorros`.`cuenta` (`cuenta_id`),
  CONSTRAINT `fk_cliente_persona1`
    FOREIGN KEY (`persona_per_cedula`)
    REFERENCES `cahorros`.`persona` (`per_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cahorros`.`creditos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cahorros`.`creditos` (
  `creditos_id` INT NOT NULL AUTO_INCREMENT,
  `creditos_aprobacion` VARCHAR(1) NOT NULL,
  `creditos_monto` DOUBLE NOT NULL,
  PRIMARY KEY (`creditos_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cahorros`.`cuenta_has_creditos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cahorros`.`cuenta_has_creditos` (
  `Cuenta_cuenta_id` INT NOT NULL,
  `Creditos_creditos_id` INT NOT NULL,
  PRIMARY KEY (`Cuenta_cuenta_id`, `Creditos_creditos_id`),
  INDEX `fk_Cuenta_has_Creditos_Creditos1_idx` (`Creditos_creditos_id` ASC) VISIBLE,
  INDEX `fk_Cuenta_has_Creditos_Cuenta1_idx` (`Cuenta_cuenta_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cuenta_has_Creditos_Creditos1`
    FOREIGN KEY (`Creditos_creditos_id`)
    REFERENCES `cahorros`.`creditos` (`creditos_id`),
  CONSTRAINT `fk_Cuenta_has_Creditos_Cuenta1`
    FOREIGN KEY (`Cuenta_cuenta_id`)
    REFERENCES `cahorros`.`cuenta` (`cuenta_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cahorros`.`librodiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cahorros`.`librodiario` (
  `lib_id` INT NOT NULL AUTO_INCREMENT,
  `lib_fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lib_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cahorros`.`recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cahorros`.`recibo` (
  `recibo_id` INT NOT NULL AUTO_INCREMENT,
  `recibo_fecha` VARCHAR(45) NOT NULL,
  `recibo_saldo` DOUBLE NOT NULL,
  PRIMARY KEY (`recibo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cahorros`.`transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cahorros`.`transaccion` (
  `transaccion_id` INT NOT NULL AUTO_INCREMENT,
  `transaccion_tipo` VARCHAR(45) NOT NULL,
  `transaccion_monto` DOUBLE NOT NULL,
  `transaccion_fecha` VARCHAR(45) NOT NULL,
  `Recibo_recibo_id` INT NOT NULL,
  `LibroDiario_lib_id` INT NOT NULL,
  PRIMARY KEY (`transaccion_id`, `Recibo_recibo_id`, `LibroDiario_lib_id`),
  INDEX `fk_Transaccion_Recibo1_idx` (`Recibo_recibo_id` ASC) VISIBLE,
  INDEX `fk_Transaccion_LibroDiario1_idx` (`LibroDiario_lib_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transaccion_LibroDiario1`
    FOREIGN KEY (`LibroDiario_lib_id`)
    REFERENCES `cahorros`.`librodiario` (`lib_id`),
  CONSTRAINT `fk_Transaccion_Recibo1`
    FOREIGN KEY (`Recibo_recibo_id`)
    REFERENCES `cahorros`.`recibo` (`recibo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cahorros`.`cuenta_has_transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cahorros`.`cuenta_has_transaccion` (
  `Cuenta_cuenta_id` INT NOT NULL,
  `Transaccion_transaccion_id` INT NOT NULL,
  PRIMARY KEY (`Cuenta_cuenta_id`, `Transaccion_transaccion_id`),
  INDEX `fk_Cuenta_has_Transaccion_Transaccion1_idx` (`Transaccion_transaccion_id` ASC) VISIBLE,
  INDEX `fk_Cuenta_has_Transaccion_Cuenta1_idx` (`Cuenta_cuenta_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cuenta_has_Transaccion_Cuenta1`
    FOREIGN KEY (`Cuenta_cuenta_id`)
    REFERENCES `cahorros`.`cuenta` (`cuenta_id`),
  CONSTRAINT `fk_Cuenta_has_Transaccion_Transaccion1`
    FOREIGN KEY (`Transaccion_transaccion_id`)
    REFERENCES `cahorros`.`transaccion` (`transaccion_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cahorros`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cahorros`.`empleado` (
  `empleado_id` INT NOT NULL AUTO_INCREMENT,
  `empleado_cargo` VARCHAR(45) NOT NULL,
  `Banco_banco_id` INT NOT NULL,
  `Banco_Horario_horario_id` INT NOT NULL,
  `persona_per_cedula` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`empleado_id`),
  INDEX `fk_Empleado_Banco1_idx` (`Banco_banco_id` ASC, `Banco_Horario_horario_id` ASC) VISIBLE,
  INDEX `fk_empleado_persona1_idx` (`persona_per_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Banco1`
    FOREIGN KEY (`Banco_banco_id` , `Banco_Horario_horario_id`)
    REFERENCES `cahorros`.`banco` (`banco_id` , `Horario_horario_id`),
  CONSTRAINT `fk_empleado_persona1`
    FOREIGN KEY (`persona_per_cedula`)
    REFERENCES `cahorros`.`persona` (`per_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cahorros`.`plancuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cahorros`.`plancuentas` (
  `plan_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`plan_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
